FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=password123
ENV MYSQL_DATABASE=AtraccionesBolivia
ENV MYSQL_REPLICATION_ROLE=master
ENV MYSQL_REPLICATION_USER=replicator
ENV MYSQL_REPLICATION_PASSWORD=replpassword
ENV MYSQL_LOG_CONSOLE=1

COPY ./config/master.cnf /etc/mysql/my.cnf
COPY ./data_csv /var/lib/mysql-files/csv
COPY ./BD/*.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
